// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/data.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
var SUPABASE_URL =
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (typeof globalThis.Deno !== "undefined" && globalThis.Deno.env.get("SUPABASE_URL")) || // eslint-disable-next-line @typescript-eslint/no-explicit-any
  "https://phsbpngyfobtieyekewp.supabase.co";
var SUPABASE_KEY =
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (typeof globalThis.Deno !== "undefined" && globalThis.Deno.env.get("SUPABASE_ANON_KEY")) || // eslint-disable-next-line @typescript-eslint/no-explicit-any
  "sb_publishable_JMQ5V0ZTb1Pme0tX-wOSDQ_9QDOcdw8";
var sb = createClient(SUPABASE_URL, SUPABASE_KEY);
async function fetchProjects(opts = {}) {
  let q = sb
    .from("public_projects_index")
    .select("slug,title,company,role,timeline,category,short_description,featured")
    .order("sort_order");
  if (opts.featuredOnly) q = q.eq("featured", true);
  const { data, error } = await q;
  if (error) throw error;
  return (data ?? []).map((p) => ({
    slug: p.slug,
    title: p.title,
    company: p.company,
    role: p.role,
    timeline: p.timeline,
    category: p.category,
    summary: p.short_description,
    featured: p.featured,
    url: `/projects/${p.slug}`,
  }));
}
async function fetchSiteInfo() {
  const { data } = await sb.from("site_settings").select("*").eq("id", 1).maybeSingle();
  return data ?? {};
}
async function fetchExperience() {
  const { data } = await sb
    .from("experience")
    .select("*")
    .eq("published", true)
    .order("sort_order");
  return data ?? [];
}
async function fetchSkills() {
  const { data } = await sb.from("skills").select("*").order("sort_order");
  const groups = {};
  for (const row of data ?? []) (groups[row.group_name] ??= []).push(row.name);
  return Object.entries(groups).map(([group, items]) => ({ group, items }));
}

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List case studies",
  description:
    "List public case-study previews. Detailed case-study content remains password-protected.",
  inputSchema: {
    featuredOnly: z.boolean().optional().describe("If true, return only featured projects."),
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ featuredOnly }) => {
    const items = await fetchProjects({ featuredOnly });
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { projects: items },
    };
  },
});

// src/lib/mcp/tools/get-about.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_about_default = defineTool3({
  name: "get_about",
  title: "About the site owner",
  description:
    "Return profile info: name, tagline, bio, location, email, socials, and skill groups.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const [siteInfo, skills] = await Promise.all([fetchSiteInfo(), fetchSkills()]);
    const about = { ...siteInfo, skills };
    return {
      content: [{ type: "text", text: JSON.stringify(about, null, 2) }],
      structuredContent: { about },
    };
  },
});

// src/lib/mcp/tools/get-experience.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_experience_default = defineTool4({
  name: "get_experience",
  title: "Work experience",
  description: "Return work experience \u2014 roles, companies, timelines, and descriptions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const experience = await fetchExperience();
    return {
      content: [{ type: "text", text: JSON.stringify(experience, null, 2) }],
      structuredContent: { experience },
    };
  },
});

// src/lib/mcp/tools/contact-inquiry.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^4.4.3";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
function getSupabase() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
  if (!url || !key) throw new Error("Backend is not configured.");
  return createClient2(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
}
var contact_inquiry_default = defineTool5({
  name: "contact_inquiry",
  title: "Submit a contact inquiry",
  description:
    "Send a message to Aman Mishra on the visitor's behalf. Use only when the visitor has explicitly asked to contact him. Include the visitor's own name, email, and message \u2014 never invented values.",
  inputSchema: {
    name: z3.string().trim().min(1).max(200).describe("Visitor's full name."),
    email: z3.string().trim().email().max(320).describe("Visitor's email address."),
    message: z3.string().trim().min(1).max(5e3).describe("The message to send."),
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, email, message }) => {
    try {
      const supabase = getSupabase();
      const { error } = await supabase
        .from("contact_inquiries")
        .insert({ name, email, message, source: "mcp" });
      if (error) {
        return {
          content: [{ type: "text", text: `Could not send: ${error.message}` }],
          isError: true,
        };
      }
      return {
        content: [
          {
            type: "text",
            text: `Thanks \u2014 your message was delivered to Aman. He'll reply to ${email}.`,
          },
        ],
        structuredContent: { delivered: true },
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Unknown error";
      return { content: [{ type: "text", text: msg }], isError: true };
    }
  },
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "aman-mishra-portfolio",
  title: "Aman Mishra \u2014 Portfolio",
  version: "0.1.0",
  instructions:
    "Tools for exploring Aman Mishra's public portfolio profile. Case-study details are password-protected; list_projects returns public previews only. Use get_about and get_experience for background, and contact_inquiry only when a visitor explicitly asks to contact him.",
  tools: [
    list_projects_default,
    get_about_default,
    get_experience_default,
    contact_inquiry_default,
  ],
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
