BEGIN;

-- The original password was generated by bcryptjs, which writes a $2b$
-- prefix. PostgreSQL pgcrypto's Blowfish verifier expects the compatible
-- $2a$ prefix. The checksum and cost stay unchanged, so visitors keep using
-- the same password and existing password-version semantics are preserved.
UPDATE public.project_access_settings
SET password_hash = '$2a$' || substr(password_hash, 5)
WHERE id = 1
  AND password_hash LIKE '$2b$%';

COMMIT;
